theme: to minima
title: **Five hundred miles**
author: Arthur
email: 414099203@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to be a programmer

# social links
twitter_username: Arthur # DO NOT include the @ character, or else the build will fail!
github_username:  Arthur # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
